# Generated by Django 5.1 on 2024-08-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tasks',
        ),
    ]
