# Generated by Django 5.1.1 on 2024-10-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cancha_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='done',
        ),
        migrations.AddField(
            model_name='tasks',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tasks',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
